# Generated by Django 2.2.2 on 2019-06-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentText', models.CharField(max_length=100)),
                ('commentedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postBody', models.CharField(max_length=200)),
                ('postedTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userPhoto', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactionType', models.CharField(choices=[('Li', 'Like'), ('Lo', 'Love'), ('Ha', 'Haha'), ('Wo', 'Wow'), ('An', 'Angry')], max_length=2)),
                ('likeUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.User')),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.Post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.User'),
        ),
        migrations.CreateModel(
            name='CommentLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactionType', models.CharField(choices=[('Li', 'Like'), ('Lo', 'Love'), ('Ha', 'Haha'), ('Wo', 'Wow'), ('An', 'Angry')], max_length=2)),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.Comment')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PostData.User'),
        ),
    ]
