# Generated by Django 2.2.2 on 2019-06-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replyId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='PostData.Comment'),
        ),
    ]
