# Generated by Django 2.2.2 on 2019-06-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0004_auto_20190627_0944'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentreactions',
            unique_together={('commentId', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='postreactions',
            unique_together={('post', 'user')},
        ),
    ]
