# Generated by Django 2.2.2 on 2019-06-27 10:15

import PostData.constant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0005_auto_20190627_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreactions',
            name='reactionType',
            field=models.CharField(choices=[(PostData.constant.Reaction('LOVE'), 'love'), (PostData.constant.Reaction('LIKE'), 'like'), (PostData.constant.Reaction('HAHA'), 'haha'), (PostData.constant.Reaction('WOW'), 'wow'), (PostData.constant.Reaction('SAD'), 'sad'), (PostData.constant.Reaction('Angry'), 'angry')], max_length=2),
        ),
        migrations.AlterField(
            model_name='postreactions',
            name='reactionType',
            field=models.CharField(choices=[(PostData.constant.Reaction('LOVE'), 'love'), (PostData.constant.Reaction('LIKE'), 'like'), (PostData.constant.Reaction('HAHA'), 'haha'), (PostData.constant.Reaction('WOW'), 'wow'), (PostData.constant.Reaction('SAD'), 'sad'), (PostData.constant.Reaction('Angry'), 'angry')], max_length=2),
        ),
    ]
