# Generated by Django 2.2.2 on 2019-06-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostData', '0008_auto_20190627_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentreactions',
            name='reactionType',
            field=models.CharField(choices=[('LOVE', 'LOVE'), ('LIKE', 'LIKE'), ('HAHA', 'HAHA'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('Angry', 'Angry')], max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='postedTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postreactions',
            name='reactionType',
            field=models.CharField(choices=[('LOVE', 'LOVE'), ('LIKE', 'LIKE'), ('HAHA', 'HAHA'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('Angry', 'Angry')], max_length=10),
        ),
    ]
